"use client";import Link from'next/link';import{useEffect,useState}from'react';import{formatDelta,formatObsDate,formatValue}from'@/lib/format';
type MetricRow={unit?:string;latest?:{date:string;value:number};delta?:number|null;history?:Array<{date:string;value:number}>};type Row={id:string;label:string;metricId?:string;children?:Row[];metric:MetricRow|null};export function ComponentExplorer({region,kind}:{region:string;kind:string}){const[data,setData]=useState<{rows:Row[]}|null>(null);const[filter,setFilter]=useState('All Components');useEffect(() => {
  fetch(`/api/inflation/${region.toLowerCase()}?kind=${kind}`, {
    cache: "no-store",
  })
    .then((r) => r.json() as Promise<{ rows: Row[] }>)
    .then(setData);
}, [region, kind]);
const rows=data?.rows??[];return <div className="component-explorer-page mx-auto max-w-7xl px-5 pb-20 pt-8 sm:px-8" data-region={region.toLowerCase()}><Link href={`/country/${region.toLowerCase()}`} className="text-sm text-[var(--accent-ink)]">← Back to inflation</Link><header className="mt-5"><div className="text-xs uppercase tracking-[.18em] text-[var(--accent-ink)]">{region} Inflation</div><h1 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-bold">{region} Inflation – {kind} Components</h1><p className="mt-2 text-sm text-[var(--muted)]">Hierarchical component view with YoY, MoM, current-year trend, release date and Detail →.</p></header><div className="mt-7 flex flex-wrap gap-2">{['All Components','Food','Energy','Core Goods','Core Services'].map(x=><button key={x} aria-pressed={filter===x} onClick={()=>setFilter(x)} className={`rounded-full px-4 py-2 text-xs font-semibold ${filter===x?'bg-[var(--ink)] text-white':'border border-[var(--line)] bg-[var(--panel)]'}`}>{x}</button>)}</div><div className="mt-6 overflow-x-auto rounded-2xl border border-[var(--line)] bg-[var(--panel)]"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-[var(--line)] text-xs uppercase tracking-wide text-[var(--muted)]"><tr><th className="px-4 py-3">Component</th><th className="px-4 py-3">Weight</th><th className="px-4 py-3">YoY</th><th className="px-4 py-3">MoM</th><th className="px-4 py-3">Current-year trend</th><th className="px-4 py-3">Last release</th><th className="px-4 py-3">Action</th></tr></thead><tbody>{rows.map((r,i)=>{const m=r.metric;return <tr key={`${r.id}-${i}`} className="border-b border-[var(--line)] last:border-0"><td className="px-4 py-3"><div className="font-medium">{r.label}</div>{r.children&&<div className="mt-1 text-[10px] text-[var(--muted)]">{r.children.length} subdivisions</div>}</td><td className="px-4 py-3 text-[var(--muted)]">—</td><td className="px-4 py-3 font-[family-name:var(--font-mono)]">{m?.unit==='percent'?formatValue(m.latest?.value,m.unit ?? "number"):'—'}</td><td className="px-4 py-3 font-[family-name:var(--font-mono)]">{m?.delta!=null?formatDelta(m.delta,m.unit ?? "number"):'—'}</td><td className="px-4 py-3 text-[var(--accent-ink)]">{m?.history?.length?'▁▂▃▅▆':'—'}</td><td className="px-4 py-3 text-xs text-[var(--muted)]">{m?.latest?.date?formatObsDate(m.latest.date):'—'}</td><td className="px-4 py-3">{r.metricId?<Link href={`/metrics/${r.metricId}`} className="font-semibold text-[var(--accent-ink)]">Detail →</Link>:<span className="text-xs text-[var(--muted)]">Component</span>}</td></tr>})}</tbody></table></div><p className="mt-4 text-xs text-[var(--muted)]">Weights are shown when the official source provides the applicable basket weight; unmapped classification nodes remain visible so the official hierarchy is preserved.</p></div>}

